### PR TITLE
Rebuild for compiler_version 9

### PR DESCRIPTION
**Pull request by h-vetinari**
Needed to resolve failing dependency resolution e.g. in https://github.com/conda-forge/scipy-feedstock/pull/153

### CODE REVIEW

**Comment by h-vetinari** [comment]
I hadn't seen #19 (which however didn't bump the linux compiler version); now opened https://github.com/conda-forge/blas-feedstock/pull/59 as well

**Comment by h-vetinari** [comment]
@isuruf, this is green. :)

**Comment by h-vetinari** [comment]
@isuruf, any objections to merging this?

**Comment by isuruf** [comment]
This wouldn't change anything as we don't use a fortran compiler here.

**Comment by h-vetinari** [comment]
This is about the `c_compiler_version`, and -- AFAICT -- the reason why things don't resolve anymore on linux for e.g. scipy. Not least because the resolution errors started on the compilers migration, and were clearly visible in the sense that, in the same [CI run](https://github.com/conda-forge/scipy-feedstock/pull/130#issuecomment-720105058), v7 resolved and v9 didn't. These resolution errors in https://github.com/conda-forge/scipy-feedstock/pull/130 & https://github.com/conda-forge/scipy-feedstock/pull/153 haven't gone away since.

**Comment by isuruf** [comment]
The only thing that would change with this PR is that the run dependency of `libgcc-ng>=7.5.0` will become `libgcc-ng>=9.3.0`. I don't see how that will help anything.

**Comment by h-vetinari** [comment]
Have a look at some of the [resolution errors](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=257289&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=594) for adding `blis` to the scipy run-reqs... I'm having a hard time coming up with a definite culprit, but `libgcc-ng` is part of the game there:
```
Package libgcc-ng conflicts for:
numpy[version='>=1.16.6,<2.0a0'] -> python[version='>=3.7,<3.8.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']
mpmath -> python -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=7.2.0']
pytest -> python[version='>=3.9,<3.10.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=7.2.0']
numpy[version='>=1.16.6,<2.0a0'] -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']
libgcc-ng[version='>=9.3.0']
python[version='>=3.7,<3.8.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=7.2.0']
blas=[build=*blis] -> liblapack==3.8.0[build=*netlib] -> libgcc-ng[version='>=9.3.0']
libcblas[version='>=3.8.0,<4.0a0'] -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']
liblapack[version='>=3.8.0,<4.0a0'] -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']
python_abi=3.7[build=*_cp37m] -> python=3.7 -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=7.2.0']
blas=[build=*blis] -> libgcc-ng[version='>=7.3.0|>=7.5.0']
libblas[version='>=3.8.0,<4.0a0'] -> libgcc-ng[version='>=7.3.0|>=7.5.0|>=9.3.0']
pytest-xdist -> python[version='>=3.5'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=7.2.0']
```

I had pinged `@conda-forge/blis` a couple of times in https://github.com/conda-forge/scipy-feedstock/pull/130 (not realising it was just you 😅), and so I just thought I'd now try fixing it myself. Looking at this from the other side, what possible downside could it have to rerender this feedstock?

**Comment by h-vetinari** [comment]
Closing as superseded by #21

**Pull request closed without merging**
